void auton(int autonToRun);
void run();
void init(int x, int y, int h);
int get_heading(int base);
void Left_7B_2G();
void Right_7B_2G();
void StartIntake();
void StopIntake();
void TestPidTurn();
void TestPidMove();
void raygoon_righ_tauton();
void Right_Solo_AWP();